apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      imagePullSecrets:
        - name: registry-creds
      containers:
        - name: angular-container
          image: shoroukimage/angular-app:1.1
          ports:
            - containerPort: 80

